# Write your MySQL query statement below
SELECT P.PRODUCT_ID, ROUND(
    -- IFNULL(SUM(U.UNIT*P.PRICE)/SUM(U.UNIT)),2
    IF(SUM(U.UNITS) IS NULL OR SUM(U.UNITS)=0,0,SUM(U.UNITS*P.PRICE)/SUM(U.UNITS)),2
)AS AVERAGE_PRICE
FROM PRICES P
LEFT JOIN UnitsSold  U
ON P.PRODUCT_ID=U.PRODUCT_ID
AND 
U.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
GROUP BY P.PRODUCT_ID