# Write your MySQL query statement below
SELECT ROUND(
    COUNT(DISTINCT A.PLAYER_ID)/
    (SELECT 
    COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY)
    ,2)
AS FRACTION
FROM
(
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_LOGIN
    FROM ACTIVITY
    GROUP BY PLAYER_ID
)AS FIRSTLOGIN
INNER JOIN ACTIVITY A
ON FIRSTLOGIN.PLAYER_ID=A.PLAYER_ID
AND A.EVENT_DATE=DATE_ADD(FIRSTLOGIN.FIRST_LOGIN, INTERVAL 1 DAY);